### ISSUE TITLE
Works for one repo but not another

### ISSUE THREAD

**Issue by idontgetoutmuch** [TerrorJack/vanilla#2]
You very kindly helped me create this script

```
version: 2
jobs:
  build:
    docker:
      - image: terrorjack/vanilla:haskell
    steps:
      - checkout
      - restore_cache:
          key: stack-deps-eek-{{ checksum "stack.yaml" }}
      - run:
          name: Update packages
          command: nix-channel --update
      - run:
          name: Building dependencies
          command: |
            nix-env -f nixpkgs.nix -iA stack
            stack --nix --no-terminal --nix build --only-snapshot --prefetch --no-haddock --test --bench --jobs=1
      - save_cache:
          paths:
            - "~/.stack"
          key: stack-deps-eek-{{ checksum "stack.yaml" }}
      - run:
          name: Building
          command: |
            stack --nix --no-terminal --nix build --pedantic
      - run:
          name: Building tests
          command: |
            stack --nix test --pedantic --no-run-tests
      - run:
          name: Running tests
          command: |
            stack --nix test
```

It works here:

https://circleci.com/gh/idontgetoutmuch/hmatrix/111

but not here

https://circleci.com/gh/idontgetoutmuch/random-fu-multivariate/2

Any ideas?
